spring:
  application:
    name: Config-Prod
eureka:
  instance:
    appname: CONFIG-SERVER-APP
    prefer-ip-address: true    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:8761/eureka
